scan_interval:
  period: 1
  unit: minutes
server_config:
  context_root: '/metrics/prometheus'
  port: 9094
directories:
  - path: '/etc/home/tls'
    file_extensions:
      - crt
      - cer
remote_endpoints:
  - path: 'https://www.farsnews.ir/'
    ca_file_path: '/etc/certificateexporter/tls/chain.crt'

