scan_interval:
  period: 1
  unit: minute
server_config:
  root_context: '/metrics/prometheus'
  port: 9094
directories:
  - path: 'F:\Personal\github\quarkus-monitoring-starter\docker-compose\tls'
    file_extension:
      - crt
      - cer
#  - path: sad
#    fileExtension:
#      - cer

