scan_interval:
  period: 1
  unit: minute
server_config:
  root_context: '/metrics/prometheus'
  port: 9094
directories:
  - path: 'F:\Personal\github\quarkus-monitoring-starter\docker-compose\tls'
    file_extension:
      - crt
      - cer
remote_endpoints:
  - path: 'https://www.farsnews.ir/'
    ca_file_path: 'C:\Users\M_Kalantari\Documents\My Received Files\fars-chain\chain.crt'
#  - path: sad
#    fileExtension:
#      - cer

